### PR TITLE
Fix for Django 1.8 (also tested on 1.7)

### PR DESCRIPTION
**Pull request by davmlaw**
File "/usr/local/lib/python2.7/dist-packages/django_dag/models.py", line 221, in edge_factory
    node_model_name = node_model._meta.module_name
AttributeError: 'Options' object has no attribute 'module_name'

### CODE REVIEW

**Comment by davmlaw** [comment]
Tested 1.6 so works on 1.6, 1.7, 1.8

**Comment by davmlaw** [comment]
This was patched (without backwards compatability) here:

https://github.com/elpaso/django-dag/commit/74165d7298202818a6b9cb099a322213b2079740

**Comment by elpaso** [comment]
If you have a better patch to propose, please make another PR.
Thanks.
